repos:
  # ----------------------------
  # Ruff (formatter only)
  # ----------------------------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5  # latest stable
    hooks:
      - id: ruff-format
